const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const state=JSON.parse(localStorage.getItem('studentAI')||'{"notes":[],"questions":0,"quiz":0}');
function save(){localStorage.setItem('studentAI',JSON.stringify(state));renderStats()}
function addMessage(text,type){const el=document.createElement('div');el.className='message '+type;el.textContent=text;$('#messages').appendChild(el);el.scrollIntoView({behavior:'smooth',block:'nearest'})}
function answer(q){const x=q.toLowerCase();let a;if(/supervised|classification|regression/.test(x))a='Supervised learning means training a model with labelled examples. The model learns a mapping from inputs to known outputs.\n\nExamples:\n• Classification → spam vs. not spam\n• Regression → predicting a house price\n\nExam point: Supervised learning uses labelled training data and is commonly evaluated with metrics such as accuracy, precision, recall, F1-score or mean squared error.';else if(/big data/.test(x))a='Big Data refers to datasets whose size, speed, or complexity makes traditional processing difficult. Remember the 5 Vs: Volume, Velocity, Variety, Veracity and Value.\n\nExam point: Hadoop is an ecosystem commonly associated with distributed storage and processing of large datasets.';else if(/dbms|database/.test(x))a='DBMS is software used to create, store, organize and retrieve data from databases. Key concepts include tables, primary keys, foreign keys, normalization, transactions and SQL.\n\nQuick revision: ACID = Atomicity, Consistency, Isolation, Durability.';else if(/stack|queue|linked list|data structure/.test(x))a='A data structure organizes data so operations can be performed efficiently.\n\nStack → LIFO (last in, first out)\nQueue → FIFO (first in, first out)\nLinked list → nodes connected through links\nHash table → key/value access using a hash function\n\nWhen studying, focus on the operation complexities and when each structure is useful.';else if(/exam|revise|study/.test(x))a='Try this 30-minute cycle:\n1. 10 min — read the core concept.\n2. 5 min — close the material and recall it.\n3. 10 min — solve questions without looking.\n4. 5 min — write a tiny revision note.\n\nThen use Quiz Me to test retention.';else a='I can help you break this topic into an exam-friendly explanation. Start by identifying: (1) the definition, (2) the main components or steps, (3) one example, and (4) a comparison or advantage/disadvantage.\n\nFor a deeper answer, paste your syllabus topic or study material here.';return a}
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();const p=$('#prompt'),q=p.value.trim();if(!q)return;$('#welcome').style.display='none';addMessage(q,'user');p.value='';state.questions++;save();setTimeout(()=>addMessage(answer(q),'ai'),250)});
$$('.suggestions button').forEach(b=>b.onclick=()=>{$('#prompt').value=b.textContent;$('#chatForm').requestSubmit()});
$$('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function showView(v){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view').forEach(x=>x.classList.remove('active'));$('#'+v+'View').classList.add('active');$('#pageTitle').textContent={chat:'Study Chat',notes:'My Notes',quiz:'Quiz Me',progress:'Progress'}[v];if(v==='notes')renderNotes();if(v==='quiz')renderQuiz()}
$('#newChat').onclick=()=>{$('#messages').innerHTML='';$('#welcome').style.display='block';showView('chat');$('#prompt').focus()}
$('#addNote').onclick=()=>{const title=prompt('Note title:');if(!title)return;const text=prompt('Write your revision note:');if(!text)return;state.notes.unshift({id:Date.now(),title,text});save();renderNotes()}
function renderNotes(){const g=$('#notesGrid');g.innerHTML=state.notes.length?state.notes.map(n=>`<article class="note"><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p><div class="note-actions"><button class="delete" data-id="${n.id}">Delete</button></div></article>`).join(''):'<div class="empty">No notes yet. Add your first revision note.</div>';$$('.delete').forEach(b=>b.onclick=()=>{state.notes=state.notes.filter(n=>n.id!=b.dataset.id);save();renderNotes()})}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const quizzes={ml:[['Which type of learning uses labelled data?',['Supervised','Unsupervised','Reinforcement','Random'],0],['Which metric is commonly used for classification?',['MSE','Accuracy','MAE','R-squared'],1],['What is overfitting?',['Model too simple','Model memorizes training data and generalizes poorly','Missing labels','Increasing dataset size'],1]],ds:[['A stack follows which principle?',['FIFO','LIFO','Random','Priority'],1],['Which structure uses nodes and links?',['Array','Linked list','Matrix','Heap'],1],['Binary search requires what?',['Unsorted data','Sorted data','A graph','A queue'],1]],dbms:[['What does SQL stand for?',['Structured Query Language','Simple Query Logic','System Queue Language','Stored Question List'],0],['Which key uniquely identifies a row?',['Foreign key','Primary key','Candidate table','Index only'],1],['Which property is part of ACID?',['Availability','Atomicity','Adaptability','Aggregation'],1]],ai:[['Which is an AI search algorithm?',['BFS','CSS','HTML','JSON'],0],['What does NLP process?',['Natural language','Only images','Hardware','Networks'],0],['An expert system typically uses?',['Knowledge base and inference','Only a database','Only sensors','A compiler'],0]]};let qi=0;function renderQuiz(){const arr=quizzes[$('#quizTopic').value];const q=arr[qi%arr.length];$('#quizCard').innerHTML=`<div class="quiz-meta"><span>Question ${(qi%arr.length)+1} / ${arr.length}</span><span>Score: ${state.quiz}</span></div><p class="quiz-question">${q[0]}</p><div class="options">${q[1].map((o,i)=>`<button class="option" data-i="${i}">${o}</button>`).join('')}</div>`;$$('.option').forEach(b=>b.onclick=()=>{const ok=+b.dataset.i===q[2];b.classList.add(ok?'correct':'wrong');if(ok)state.quiz++;save();setTimeout(()=>{qi++;renderQuiz()},500)})}
$('#quizTopic').onchange=()=>{qi=0;renderQuiz()};$('#clearData').onclick=()=>{if(confirm('Clear your local notes and activity?')){localStorage.removeItem('studentAI');location.reload()}};
function renderStats(){const n=state.notes.length,q=state.questions,s=state.quiz;$('#statQuestions').textContent=q;$('#statNotes').textContent=n;$('#statQuiz').textContent=s;const pct=Math.min(100,q*5+n*10+s*5);$('#progressBar').style.width=pct+'%';$('#progressText').textContent=pct+'% activity'}
renderStats();renderNotes();renderQuiz();