import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BookOpen, FileText, MessageSquare, Brain, BarChart3, Upload, Send, Settings, Plus, Sparkles, LogIn, LogOut, Trash2 } from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
const tabs = [['chat','Study Chat',MessageSquare],['pdf','PDF Study',FileText],['notes','My Notes',BookOpen],['quiz','Quiz Me',Brain],['progress','Progress',BarChart3]];

function App(){
 const [tab,setTab]=useState('chat'),[question,setQuestion]=useState(''),[messages,setMessages]=useState([]),[pdf,setPdf]=useState(null),[pdfText,setPdfText]=useState(''),[documentId,setDocumentId]=useState(null),[loading,setLoading]=useState(false),[notes,setNotes]=useState([]),[questions,setQuestions]=useState(0),[token,setToken]=useState(localStorage.getItem('studentai-token')||''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authMode,setAuthMode]=useState('login'),[authError,setAuthError]=useState('');
 const authHeaders=token?{Authorization:`Bearer ${token}`} : {};
 useEffect(()=>{if(token) loadNotes()},[token]);
 async function loadNotes(){const r=await fetch(`${API}/api/notes`,{headers:authHeaders});if(r.ok)setNotes(await r.json())}
 async function auth(){setAuthError('');try{const r=await fetch(`${API}/api/auth/${authMode==='login'?'login':'register'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw Error(d.detail||'Authentication failed');localStorage.setItem('studentai-token',d.access_token);setToken(d.access_token);setPassword('')}catch(e){setAuthError(e.message)}}
 function logout(){localStorage.removeItem('studentai-token');setToken('');setNotes([])}
 async function ask(q=question,task='answer',context=pdfText){const text=q.trim();if(!text||loading)return;setQuestion('');setMessages(m=>[...m,{role:'user',text}]);setLoading(true);setQuestions(n=>n+1);try{const r=await fetch(`${API}/api/chat`,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders},body:JSON.stringify({question:text,context,document_id:documentId,task,semantic:true})});const d=await r.json();if(!r.ok)throw Error(d.detail||'Request failed');setMessages(m=>[...m,{role:'ai',text:d.answer,model:d.model,sources:d.sources||[]}]);}catch(e){setMessages(m=>[...m,{role:'ai',text:`Backend error: ${e.message}`}])}finally{setLoading(false)}}
 async function uploadPdf(file){if(!file)return;setPdf(file);setLoading(true);try{const f=new FormData();f.append('file',file);const r=await fetch(`${API}/api/pdf/extract`,{method:'POST',body:f});const d=await r.json();if(!r.ok)throw Error(d.detail||'PDF extraction failed');setPdfText(d.text);setDocumentId(d.document_id);setMessages(m=>[...m,{role:'ai',text:`Loaded ${d.filename} — ${d.pages} pages. ${d.indexed_chunks||0} chunks indexed for semantic search.`}]);}catch(e){setMessages(m=>[...m,{role:'ai',text:e.message}])}finally{setLoading(false)}}
 async function addNote(){const title=prompt('Note title');const body=prompt('Revision note');if(!title||!body)return;if(!token){alert('Login to save notes permanently.');return}const r=await fetch(`${API}/api/notes`,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders},body:JSON.stringify({title,content:body})});if(r.ok)loadNotes()}
 async function deleteNote(id){const r=await fetch(`${API}/api/notes/${id}`,{method:'DELETE',headers:authHeaders});if(r.ok)loadNotes()}
 return <div className="shell"><aside className="sidebar"><div className="brand"><span><Sparkles size={18}/></span> StudentAI</div><button className="new" onClick={()=>setMessages([])}><Plus size={17}/> New session</button><div className="label">WORKSPACE</div>{tabs.map(([id,name,Icon])=><button key={id} className={`nav ${tab===id?'active':''}`} onClick={()=>setTab(id)}><Icon size={18}/>{name}</button>)}<div className="side-bottom"><div className="ai-badge"><Sparkles size={16}/><div><b>RAG Study Engine</b><small>PDF → semantic retrieval → AI</small></div></div></div></aside>
 <main className="main"><header><div><div className="eyebrow">AI STUDY WORKSPACE</div><h1>{tabs.find(x=>x[0]===tab)?.[1]}</h1></div><div className="account">{token?<button className="secondary" onClick={logout}><LogOut size={16}/> Logout</button>:<button className="secondary" onClick={()=>setTab('login')}><LogIn size={16}/> Login</button>}<button className="icon"><Settings size={19}/></button></div></header>
 {tab==='login'&&<section className="content"><div className="card auth"><Sparkles size={30}/><h2>{authMode==='login'?'Welcome back':'Create your StudentAI account'}</h2><input placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password (8+ characters)" type="password" value={password} onChange={e=>setPassword(e.target.value)}/>{authError&&<p className="error">{authError}</p>}<button className="primary" onClick={auth}>{authMode==='login'?<LogIn size={17}/>:<Plus size={17}/>} {authMode==='login'?'Login':'Register'}</button><button className="link" onClick={()=>setAuthMode(authMode==='login'?'register':'login')}>{authMode==='login'?'Need an account? Register':'Already have an account? Login'}</button></div></section>}
 {tab==='chat'&&<section className="content chat"><div className="hero"><div className="orb"><Sparkles/></div><h2>Study smarter. Build understanding.</h2><p>Ask questions, upload lecture PDFs, create revision notes and practice with AI.</p><div className="chips">{['Explain supervised learning simply','Give me 5 DBMS revision questions','Explain Big Data for an exam','Make a 7-day study plan'].map(x=><button key={x} onClick={()=>ask(x)}>{x}</button>)}</div></div><div className="messages">{messages.map((m,i)=><div key={i} className={`msg ${m.role}`}><div className="msg-label">{m.role==='ai'?'StudentAI':'You'}</div><div>{m.text}</div>{m.sources?.length>0&&<div className="sources"><b>Sources</b>{m.sources.map((s,j)=><small key={j}>Page {s.page}: {s.preview}</small>)}</div>}{m.model&&<small>Model: {m.model}</small>}</div>)}{loading&&<div className="msg ai"><div className="msg-label">StudentAI</div>Thinking…</div>}</div><div className="composer"><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}}} placeholder="Ask anything about your studies…"/><button onClick={()=>ask()}><Send size={18}/></button></div></section>}
 {tab==='pdf'&&<section className="content"><div className="card upload"><Upload size={32}/><h2>Study from a PDF</h2><p>Upload lecture notes, textbooks or question papers. StudentAI extracts, chunks and semantically indexes the document.</p><label className="drop"><Upload size={20}/> Choose PDF<input type="file" accept="application/pdf" onChange={e=>uploadPdf(e.target.files?.[0])}/></label>{pdf&&<div className="file">{pdf.name}<span>{pdfText.length.toLocaleString()} characters</span></div>}<div className="actions"><button className="primary" disabled={!pdfText||loading} onClick={()=>ask('Create an exam-ready summary with key concepts, definitions, important steps/formulas and likely questions.','summary',pdfText)}><Sparkles size={17}/> Summarize PDF</button><button className="secondary" onClick={()=>{setPdf(null);setPdfText('');setDocumentId(null)}}>Clear</button></div></div></section>}
 {tab==='notes'&&<section className="content"><div className="section-title"><div><h2>My Notes</h2><p>{token?'Saved to your account.':'Login to persist notes across devices.'}</p></div><button className="primary" onClick={addNote}><Plus size={17}/> Add note</button></div><div className="grid">{notes.map(n=><article className="note" key={n.id}><div><h3>{n.title}</h3><p>{n.content}</p></div><button className="icon" onClick={()=>deleteNote(n.id)}><Trash2 size={16}/></button></article>)}{!notes.length&&<div className="empty">No saved notes yet.</div>}</div></section>}
 {tab==='quiz'&&<section className="content"><div className="card quiz"><Brain size={30}/><h2>Quiz mode</h2><p>Generate exam-style questions from your current PDF or any subject.</p><button className="primary" onClick={()=>{setTab('chat');ask(pdfText?'Create 5 multiple-choice questions from this PDF.':'Create 5 multiple-choice questions on Machine Learning with answers and explanations.','quiz',pdfText)}}><Sparkles size={17}/> Generate AI Quiz</button></div></section>}
 {tab==='progress'&&<section className="content"><div className="stats"><div><span>AI questions</span><b>{questions}</b></div><div><span>Saved notes</span><b>{notes.length}</b></div><div><span>PDF loaded</span><b>{pdf?1:0}</b></div></div><div className="card"><h2>Your study loop</h2><p>Upload → Understand → Ask → Note → Quiz → Review.</p><div className="bar"><span style={{width:`${Math.min(100,questions*10+notes.length*15)}%`}}/></div></div></section>}
 </main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
